-- Database Schema for Rengas Admin

CREATE TABLE Products (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Sku NVARCHAR(50) NOT NULL UNIQUE,
    Category NVARCHAR(100) NOT NULL,
    Name NVARCHAR(255) NOT NULL,
    Uom NVARCHAR(50) NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    ImageUrl NVARCHAR(1000) NULL,
    Description NVARCHAR(MAX) NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Orders (
    Id NVARCHAR(50) PRIMARY KEY,
    CustomerName NVARCHAR(255) NOT NULL,
    Phone NVARCHAR(50) NOT NULL,
    OrderDate DATETIME NOT NULL,
    TotalItems INT NOT NULL,
    TotalAmount DECIMAL(18,2) NOT NULL,
    Status NVARCHAR(50) NOT NULL,
    Address NVARCHAR(1000) NOT NULL,
    Tin NVARCHAR(100) NOT NULL
);
